### DISCUSSION TITLE
OpenTofu support

### DISCUSSION THREAD

**Discussion by kinseii** [shalb/cluster.dev#289] [Ideas]
Hi everybody!

I would like to share that replacing the value of the `CDEV_TF_BINARY` variable with `tofu`, works like a charm.
Have you tested OpenTofu with cluster.dev? I would like to be able to encrypt credentials in state files, and OpenTofu can do that, whereas in TerraForm you have to use the commercial version. I may try to do this myself in the near future. Also, TerraForm forbids selling the code as a SaaS service, even though it is not necessary for  me, but it will be an additional incentive to use cluster.dev together with OpenTofu. I think you should emphasize this in your advertising.
```
name: dev
    kind: Project
    backend: aws-backend
    variables:
      organization: cluster-dev
      region: eu-central-1
      state_bucket_name: cluster-dev-gha-tests
    exports:
      CDEV_TF_BINARY: "tofu"
```
