### ISSUE TITLE
Timeout while deploying the k8s addons

### ISSUE THREAD

**Issue by ironreality** [shalb/cluster.dev#103]
**Problem:**

**Cluster.dev Version:**

0.0.3

**Cluster.dev Config:**

```yaml
installed: true
name: cna-vsurzhyk-test
provider:
  type: aws
  region: eu-central-1
  availability_zones:
    - eu-central-1b
    - eu-central-1c
  vpc: create
  domain: test.vsurzhyk.cloud
  provisioner:
    type: eks
    version: 1.16
    node_group:
      - name: spot-group
        type: spot
        asg_max_size: 3
        root_volume_size: 50
        kubelet_extra_args: --node-labels=node.kubernetes.io/lifecycle=spot
      - name: on-demand-group
        instance_type: t3.medium
        asg_max_size: 3
        root_volume_size: 20
        kubelet_extra_args: --node-labels=node.kubernetes.io/lifecycle=on-demand
apps:
  - /kubernetes/apps/samples
```

Constantly getting timeouts while trying to deploy a test stack:

```
./bin/reconciler -config cluster.yaml
...
16:53:13.025 [INFO] [cluster='cna-vsurzhyk-test-local'][dir='./terraform/aws/addons'][cmd='terraform apply  -compact-warnings -input=f
alse -auto-approve tfplan'] executing in progress... 5m55s
16:53:13.791 [FATAL] Error occurred during reconciliation of cluster exit status 1, output:

Error: Error running command 'kubectl apply --kubeconfig /var/folders/t4/x_b4bh4s75g13h16tjrc7rnw0000gp/T/cluster-dev-addons-400408737
/kube_config -f https://github.com/operator-framework/operator-lifecycle-manager/releases/download/0.15.1/crds.yaml && kubectl apply -
-kubeconfig /var/folders/t4/x_b4bh4s75g13h16tjrc7rnw0000gp/T/cluster-dev-addons-400408737/kube_config -f https://github.com/operator-f
ramework/operator-lifecycle-manager/releases/download/0.15.1/olm.yaml && for resource in catalog-operator olm-operator packageserver;
do kubectl --kubeconfig /var/folders/t4/x_b4bh4s75g13h16tjrc7rnw0000gp/T/cluster-dev-addons-400408737/kube_config rollout status -n ol
m -w deploy $resource; done': exit status 1. Output: customresourcedefinition.apiextensions.k8s.io/catalogsources.operators.coreos.com
 configured
customresourcedefinition.apiextensions.k8s.io/clusterserviceversions.operators.coreos.com configured
customresourcedefinition.apiextensions.k8s.io/installplans.operators.coreos.com configured
customresourcedefinition.apiextensions.k8s.io/operatorgroups.operators.coreos.com configured
customresourcedefinition.apiextensions.k8s.io/subscriptions.operators.coreos.com configured
namespace/olm unchanged
namespace/operators unchanged
serviceaccount/olm-operator-serviceaccount unchanged
clusterrole.rbac.authorization.k8s.io/system:controller:operator-lifecycle-manager unchanged
clusterrolebinding.rbac.authorization.k8s.io/olm-operator-binding-olm unchanged
deployment.apps/olm-operator configured
deployment.apps/catalog-operator configured
clusterrole.rbac.authorization.k8s.io/aggregate-olm-edit unchanged
clusterrole.rbac.authorization.k8s.io/aggregate-olm-view unchanged
operatorgroup.operators.coreos.com/global-operators unchanged
operatorgroup.operators.coreos.com/olm-operators unchanged
catalogsource.operators.coreos.com/operatorhubio-catalog unchanged                                                          [850/2396]
error: deployment "catalog-operator" exceeded its progress deadline
error: deployment "olm-operator" exceeded its progress deadline
Error from server (NotFound): deployments.apps "packageserver" not found

Error: timed out waiting for the condition

  on cert-manager.tf line 28, in resource "helm_release" "cert_manager":
  28: resource "helm_release" "cert_manager" {

Error: timed out waiting for the condition

  on external-dns.tf line 11, in resource "helm_release" "external-dns":
  11: resource "helm_release" "external-dns" {

```
