### ISSUE TITLE
Remote template not updates, when branch changing. 

### ISSUE THREAD

**Issue by romanprog** [shalb/cluster.dev#109]
Check working with branches in template url "?ref=branch"

**Cluster.dev Version:**

**Cluster.dev Config:**

```yaml
name: k3s-test
template: https://github.com/shalb/cdev-aws-k3s?ref=branch_name
kind: infrastructure
backend: aws-backend
variables:
  bucket: {{ .project.variables.state_bucket_name }}
  region: {{ .project.variables.region }}
```
