### ISSUE TITLE
Plan is not show diff for files created by 'create_files' options in terraform modules.

### ISSUE THREAD

**Issue by romanprog** [shalb/cluster.dev#191]
Plan is not show diff for files created by 'create_files' options in terraform modules.

**Problem:**

**Cluster.dev Version:** 
v0.7.14

**Cluster.dev Config:**

```yaml
  - name: eks
    type: tfmodule
    providers:
    create_files:
    - file: ./kubernetes_provider.tf
      mode: 0644
      content: |
{{ readFile "./files/kube_provider.tf" | indent 8 }}
```
