### ISSUE TITLE
Add description for units and stack templates. Show descriptions in cdev project info

### ISSUE THREAD

**Issue by romanprog** [shalb/cluster.dev#200]
Example:

```yaml
...
  -
    name: r53
    type: tfmodule
    source: terraform-aws-modules/route53/aws//modules/zones
    version: "~> 2.0"
    description: "Creates route53 zone for cluster technical domains"
    inputs:
      zones:
       - dev.example.com
...
```

**What would you like to add**

**Why is this needed**

**Comments**
