### ISSUE TITLE
Add dependencies between stacks

### ISSUE THREAD

**Issue by romanprog** [shalb/cluster.dev#201]
Example: 
```yaml
name: stack1
template: ./template1/
kind: Stack
backend: aws-backend
variables:
  foo: bar
---
name: stack2
template: ./template1/
kind: Stack
backend: aws-backend
depends_on: stack1
variables:
  foo: bar

```
