### ISSUE TITLE
Support for required_providers block inside terraform

### ISSUE THREAD

**Issue by romanprog** [shalb/cluster.dev#202]
Now (deprecated in terraform >1.0):
```
provider "aws" {
  region  = "eu-central-1"
  version = "4.67.0"
}
```
Should be: 
```
provider "aws" {
  region  = "eu-central-1"
}

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.0"
    }
  }
}
```
Cdev unit code example:
```
  -
    name: redis-{{ $name }}
    type: tfmodule
    providers:
    - aws:
        region: {{ $variables.region }}
    required_providers:
    - aws:
        source: "hashicorp/aws"
        version: "4.67.0"
    source: cloudposse/elasticache-redis/aws
    version: "0.49.0"
    inputs:
      zone_id: []
```

**What would you like to add**

**Why is this needed**

**Comments**
