### ISSUE TITLE
cdev plan show <default namespace> instead of namespace 

### ISSUE THREAD

**Issue by romanprog** [shalb/cluster.dev#209]
cdev version v0.7.16
build timestamp: 2023-06-28T14:11:18+0300

unit:

```
  -
    name: mongodb-backups-sa
    type: k8s-manifest
    apply_template: true
    kubeconfig: {{ .variables.kubeconfig_path }}
    namespace: {{ .variables.namespace }}
    path: ./files/mongodb-backups-sa.yaml

```

manifest:

```
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: {{ remoteState "this.mongodb-backups-role.iam_role_arn" }}
  name: mongodb-backups

```

problem (not fatal, only error in plan):

```
13:30:46 [INFO] Planning unit 'persistent.mongodb-backups-sa':
 {
+ manifests: {
+  ServiceAccount.<default namespace>.mongodb-backups: {
+   apiVersion: "v1",

```
