### ISSUE TITLE
Specifying the context for `helm` and `k8s-manifest` units

### ISSUE THREAD

**Issue by kinseii** [shalb/cluster.dev#257]
**What would you like to add**
Need to be able to specify the cluster context from the kubernetes configuration file. This corresponds to the parameter at the `helm` and `kubectl` providers:
- https://registry.terraform.io/providers/hashicorp/helm/latest/docs#config_context
- https://registry.terraform.io/providers/alekc/kubectl/latest/docs#config_context

**Why is this needed**
Since we are using many clusters, it is not at all convenient to manually switch the context of a cluster.

**Comment by romanprog** [comment]
Will be implemented for the `helm` units in the next release.

This is already available for `kubernetes` unit type. See the provider_conf configuration block. provider_conf - configuration block that describes authorization in Kubernetes. Supports the same arguments as the Terraform Kubernetes provider. It is allowed to use the remoteState function and Cluster.dev templates within the block.

https://docs.cluster.dev/units-kubernetes/
for exfmple: 
```
name: <UNIT_NAME>
type: kubernetes
source: <YAML_PATH>
provider_conf:
  host: k8s.example.com
  config_context: "dev-one"
```
