### ISSUE TITLE
Local state unlock error

### ISSUE THREAD

**Issue by romanprog** [shalb/cluster.dev#267]
**Problem:**
cdev apply
11:25:16 [INFO] Checking for newer releases...
11:25:16 [FATAL] Fatal error: state is locked by another process

cdev state unlock
11:25:57 [INFO] Checking for newer releases...
11:25:57 [INFO] Unlocking state...       
11:25:57 [FATAL] Fatal error: state unlock: remove /home/arti/shalb/cluster.dev/tests/k8s/.cluster.dev/states/cdev-state.lock: no such file or directory

**Cluster.dev Version:**

**Cluster.dev Config:**

```yaml
name: dev
kind: Project
backend: default
variables:
  organization: cluster-dev
```
