### ISSUE TITLE
cdev crash use ctrl+c whenunit apply 

### ISSUE THREAD

**Issue by romanprog** [shalb/cluster.dev#268]
**Problem:**
```bash
11:24:46 [INFO] [kube-helm][cert-manager-issuer][apply] executing in progress... 0s     
^Cpanic: send on closed channel

goroutine 35 [running]:
os/signal.process({0x32211d8?, 0x4723110})
        /usr/local/go/src/os/signal/signal.go:245 +0x17f
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x29
created by os/signal.Notify.func1.1 in goroutine 1
        /usr/local/go/src/os/signal/signal.go:151 +0x1f
```
**Cluster.dev Version:**

**Cluster.dev Config:**

```yaml
name: local-template
kind: StackTemplate
cliVersion: "~>0.9.2"
units:
  -
    name: consul
    type: helm
    source:
      repository: "https://charts.bitnami.com/bitnami"
      chart: "consul"
      version: "10.9.12"
    provider_conf: {{ insertYAML .variables.k8s_conf }}
    additional_options:
      namespace: default
      create_namespace: true
    values:
      - file: ./values/consul.yaml
        apply_template: true
```
