### ISSUE TITLE
Multiple backends

### ISSUE THREAD

**Issue by kinseii** [shalb/cluster.dev#276]
We have multiple subscriptions in a cloud provider and we would like to store the state files for each StackTemplate in separate storages (backends). The documentation says (https://docs.cluster.dev/structure-project):
```
backend-name of the backend that will be used to store the cluster.dev state of the current project. Optional.
```
That is, it seems to be the way it was intended, since this parameter is optional in the Project. However, the `validate` and `plan` commands produce an error:
```
01:16:46 [FATAL] Project configuration check: fail
load base configuration: loading project: error in project config: backend is not defined. To use default local backend, set 'backend: default' option
```

Thus I can't specify multiple backends. If this is not a bug, I would like to request such a feature, thank you very much!

**Comment by romanprog** [comment]
Hello.
You can use multiple backends for terraform states (configured in `kind: stack` ). The backend is tied to the stack.
But cdev's own state (configured in `project.yaml`, `kind: project` ) can be stored only in one backend.
Here is a conditional example:
project.yaml
```yaml
name: example
kind: Project
backend: aws-backend # save cdev state in aws s3
variables:
  organization: cluster-dev
  region: eu-central-1
  state_bucket_name: cluster-dev-gha-tests
```

stack.yaml
```yaml
name: aws-backend
kind: Backend
provider: s3
spec:
  bucket: {{ .project.variables.state_bucket_name }}
  region: {{ .project.variables.region }}
---
name: azurerm-backend
kind: backend
provider: azurerm
spec:
  resource_group_name: "StorageAccount-ResourceGroup"
  storage_account_name: "example"
  container_name: "cdev-states"
---
name: aws-stack
template: https://...
kind: Stack
backend: aws-backend # save tf states in aws s3
---
name: azure-stack
template: https://...
kind: Stack
backend: azurerm-backend # save tf states in azure 
```

Does this answer the question?
