### ISSUE TITLE
The kubernetes unit does not find the source file if it is above the current directory

### ISSUE THREAD

**Issue by kinseii** [shalb/cluster.dev#277]
**Problem:**
The kubernetes unit does not find the source file if it is above the current directory (with relative path `../`):
```
---
kind: StackTemplate
name: service
units:
  - name: test-configmap
    type: kubernetes
    provider_conf:
      config_context: {{ .variables.cluster_name }}
    source: ../../_templates/test-configmap/test-configmap.yaml
```
Error output:
```
19:25:12 [FATAL] Fatal error: load project configuration: read units: stack 'qwerty-aks-us-1', reading units: reading kubernetes unit 'qwerty-aks-us-1.test-configmap': reading kubernetes manifests form source '../../_templates/test-configmap/test-configmap.yaml': stat ../../_templates/test-configmap/test-configmap.yaml: no such file or directory
Unit data:
name: test-configmap
provider_conf:
    config_context: qwerty-aks-us-1
source: ../../_templates/test-configmap/test-configmap.yaml
type: kubernetes
```
If you don't use exit above the current directory, everything works. Example:
```
kind: StackTemplate
name: service
units:
  - name: test-configmap
    type: kubernetes
    provider_conf:
      config_context: {{ .variables.cluster_name }}
    source: ./test-configmap/test-configmap.yaml
```

**Cluster.dev Version:**
cdev version v0.9.5
