### ISSUE TITLE
Variables in Project and Stack do not support nested objects

### ISSUE THREAD

**Issue by kinseii** [shalb/cluster.dev#281]
**What would you like to add**
If I try to use a variable as `{{ .variables.network.dev }}`, cdev gives an error:
`[FATAL] Fatal error: load project configuration: prepare objects: template: main:9: bad character U+002D '-'`
```
---
kind: StackTemplate
name: qwerty
units:
  - name: qwerty
    type: tfmodule
    source: ../../../qwerty
    inputs:
      network: {{ insertYAML .variables.network.dev }}
```
```
---
kind: Stack
name: qwerty-aks-us-1
template: ./qwerty/aks-us-1
backend: qwerty
variables:
  network:
    dev: 
      ip: 1.1.1.1
      mask: 1.1.1.1
    prod:
      ip: 2.2.2.2
      mask: 2.2.2.2
```
