### ISSUE TITLE
Implement DigitalOcean Kubernetes Provisioner

### ISSUE THREAD

**Issue by voatsap** [shalb/cluster.dev#56]
We need to implement DigitalOcean Provisioner support:

```
cluster:
  installed: true
  name: do-test
  cloud:
    provider: do
    region: fra-1
    project: default
    domain: create
  provisioner:
    type: digitalocean-kubernetes
    version: v1.16-do.1
    nodeCount: 3
    nideSize: s2vcpu-2gb
    autoscalling: true
    autoscale_min: 3
    autoscale_max: 5
  addons:
    nginx-ingress: true
    cert-manager: true
  apps:
    - /kubernetes/apps/samples
```
Should be implemented:
1. Create a storage for remote Terraform state at DigitalOcean Spaces (for refference [AWS state Could be used](https://github.com/shalb/cluster.dev/tree/master/terraform/aws/backend)
2. Create or define a `project` as we have in [AWS VPC](https://github.com/shalb/cluster.dev/tree/master/terraform/aws/vpc)
3. Create or define dns zone on DO DNS service as example: user.cluster.dev
4. Deploy cluster itself based on DigitalOcean Managed Kubernetes, (should be done as a separate external module) but invoked during reconcilation job.
5. Deploy nginx-ingress/cert-manager/external-dns/argo-cd as addons to Kubernetes
