### ISSUE TITLE
Implement setting VPC

### ISSUE THREAD

**Issue by voatsap** [shalb/cluster.dev#7]
If vpc is set in yaml:
```
cluster:
  name: minikube-aws
  installed: true
  cloud: 
    provider: aws
    region: eu-central-1
    vpc: default
```
It should take in account next action:
`vpc: default` # (existing behavior) use existing VPC 
`vpc:  id-223b3a` # set as the VPC defined in value
`vpc: create` # Basic VPC should be created by https://github.com/terraform-aws-modules/terraform-aws-vpc
